
on:
  workflow_run:
    workflows:
      - Trigger build
    types:
      - completed
jobs:
  build:
    runs-on: k8s-runner-build

    if: ${{ github.event.workflow_run.conclusion != 'skipped' }}
    
steps:
- id: 'auth'
  name: 'Authenticate to Google Cloud'
  uses: 'google-github-actions/auth@v0.4.0'
  with:
    workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
    service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
